#!/bin/bash

# Changes local to the machine (typically my monitor setup)
#
# Example contents:
#
#     #!/bin/bash
#
#     # Set output layout
#     riverctl spawn "wlr-randr \
#         --output DP-4 --mode 1920x1080 \
#         --output DP-3 --mode 1920x1080 --left-of DP-4 --transform 90 \
#         --output HDMI-A-1 --mode 3840x2160 --right-of DP-4 --scale 2\
#     "
here=$(dirname $(realpath $0))
[ -f $here/local.sh ] && source $here/local.sh

riverctl map normal Super D spawn "bemenu-run --fn terminus 11 --hf '#D78787' --tf '#D9D9D9' -p '$'"
riverctl map normal Super Return spawn foot

riverctl map normal Super Q close
riverctl map normal Super+Control+Shift Q exit

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super N focus-view next
riverctl map normal Super E focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift N swap next
riverctl map normal Super+Shift E swap previous

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Super+Return to bump the focused view to the top of the layout stack
riverctl map normal Super+Shift Return zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super I send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift I send-layout-cmd rivertile "main-count -1"

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt N move down 100
riverctl map normal Super+Alt E move up 100
riverctl map normal Super+Alt I move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control N snap down
riverctl map normal Super+Alt+Control E snap up
riverctl map normal Super+Alt+Control I snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift N resize vertical 100
riverctl map normal Super+Alt+Shift E resize vertical -100
riverctl map normal Super+Alt+Shift I resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+Space to toggle float
riverctl map normal Super Space toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
    riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioPlay  spawn 'mpc toggle'
    riverctl map $mode None XF86AudioPrev  spawn 'mpc prev'
    riverctl map $mode None XF86AudioNext  spawn 'mpc next'

    # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done

# Set background and border color
riverctl background-color 0x1C1C1C
riverctl border-width 1
riverctl border-color-focused 0x909090
riverctl border-color-unfocused 0x303030

# Set keyboard repeat rate
riverctl keyboard-layout -variant colemak us
riverctl set-repeat 100 300

# Hide mouse
riverctl hide-cursor timeout 2000

riverctl rule-add -app-id 'mpv' float
riverctl rule-add -app-id 'imv' float

# Ensure ssd is set
riverctl rule-add -app-id 'com.mitchellh.ghostty' ssd
riverctl rule-add -app-id 'librewolf' ssd
riverctl rule-add -app-id 'firefox' ssd
riverctl rule-add -app-id 'thunderbird' ssd
riverctl rule-add -app-id 'steam' ssd
riverctl rule-add -app-id 'org.pwmt.zathura' ssd

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 0 -outer-padding 0 &

killall dam clock
[ $(ps -aux | grep dam | wc -l) -gt 1 ] || riverctl spawn "$here/dam/clock | $here/dam/dam"

[ $(ps -aux | grep dunst | wc -l) -gt 1 ] || riverctl spawn "dunst"

[ $(ps -aux | grep gammastep | wc -l) == 2 ] || riverctl spawn "gammastep -l 51.5:0"
